pipeline {
  agent {
    docker { image 'node:16-alpine' }
  }
  stages {
    stage('Test') {
      steps {
        sh 'mvn clean install
        -Dmaven.test.skip=true
        -Dtest=maven -f Java_helloworld.java '
      }
    }
  }
}
